In [1]:
import os
import pandas as pd
from sklearn.svm import SVC
import numpy as np
from sklearn.model_selection import GridSearchCV
import time
import joblib
import sys
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from utils.evaluate_model import evaluate_model

In [2]:
X_train = pd.read_csv('../data/train_features.csv')
X_test = pd.read_csv('../data/test_features.csv')

In [3]:
X_train

time_in_hospital  n_lab_procedures  n_procedures  n_medications  \
0              0.615385          0.580357      0.166667       0.333333   
1              0.076923          0.339286      0.166667       0.115385   
2              0.000000          0.196429      0.000000       0.025641   
3              0.307692          0.473214      0.666667       0.256410   
4              0.230769          0.473214      0.000000       0.102564   
...                 ...               ...           ...            ...   
17495          0.461538          0.383929      0.000000       0.333333   
17496          0.230769          0.544643      0.000000       0.410256   
17497          0.153846          0.107143      0.166667       0.397436   
17498          0.538462          0.508929      0.666667       0.217949   
17499          0.000000          0.392857      0.666667       0.141026   

       n_outpatient  n_inpatient  n_emergency  glucose_test  a1ctest  change  \
0          0.000000     0.000000          0.0           0.0      1.0       1   
1          0.000000     0.066667          0.0           0.0      0.0       0   
2          0.000000     0.000000          0.0           0.0      2.0       1   
3          0.000000     0.000000          0.0           0.0      1.0       0   
4          0.000000     0.066667          0.0           0.0      2.0       0   
...             ...          ...          ...           ...      ...     ...   
17495      0.148148     0.200000          0.0           0.0      0.0       0   
17496      0.000000     0.133333          0.0           0.0      0.0       1   
17497      0.000000     0.000000          0.0           0.0      0.0       1   
17498      0.000000     0.000000          0.0           0.0      2.0       1   
17499      0.000000     0.066667          0.0           0.0      0.0       1   

       ...  diag_2_other  diag_2_respiratory  diag_3_circulatory  \
0      ...           0.0                 0.0                 0.0   
1      ...           0.0                 0.0                 0.0   
2      ...           1.0                 0.0                 0.0   
3      ...           0.0                 0.0                 0.0   
4      ...           0.0                 0.0                 1.0   
...    ...           ...                 ...                 ...   
17495  ...           1.0                 0.0                 0.0   
17496  ...           0.0                 1.0                 0.0   
17497  ...           0.0                 1.0                 0.0   
17498  ...           0.0                 0.0                 0.0   
17499  ...           0.0                 0.0                 1.0   

       diag_3_diabetes  diag_3_digestive  diag_3_injury  diag_3_missing  \
0                  0.0               0.0            0.0             0.0   
1                  1.0               0.0            0.0             0.0   
2                  0.0               0.0            0.0             0.0   
3                  0.0               0.0            0.0             0.0   
4                  0.0               0.0            0.0             0.0   
...                ...               ...            ...             ...   
17495              0.0               0.0            0.0             0.0   
17496              0.0               0.0            0.0             0.0   
17497              1.0               0.0            0.0             0.0   
17498              0.0               0.0            0.0             0.0   
17499              0.0               0.0            0.0             0.0   

       diag_3_musculoskeletal  diag_3_other  diag_3_respiratory  
0                         0.0           1.0                 0.0  
1                         0.0           0.0                 0.0  
2                         0.0           1.0                 0.0  
3                         0.0           1.0                 0.0  
4                         0.0           0.0                 0.0  
...                       ...           ...

In [4]:
X_test

time_in_hospital  n_lab_procedures  n_procedures  n_medications  \
0             0.000000          0.303571      0.000000       0.076923   
1             0.076923          0.080357      1.000000       0.217949   
2             0.846154          0.517857      0.166667       0.179487   
3             0.076923          0.276786      0.000000       0.230769   
4             0.000000          0.419643      0.000000       0.217949   
...                ...               ...           ...            ...   
7495          0.230769          0.303571      0.000000       0.179487   
7496          0.307692          0.348214      0.166667       0.141026   
7497          0.230769          0.410714      0.500000       0.256410   
7498          0.153846          0.339286      0.000000       0.141026   
7499          1.000000          0.151786      0.333333       0.076923   

      n_outpatient  n_inpatient  n_emergency  glucose_test  a1ctest  change  \
0         0.037037     0.133333          0.0           0.0      0.0       0   
1         0.000000     0.000000          0.0           0.0      0.0       0   
2         0.000000     0.000000          0.0           0.0      0.0       0   
3         0.000000     0.000000          0.0           0.0      0.0       0   
4         0.000000     0.000000          0.0           0.0      0.0       1   
...            ...          ...          ...           ...      ...     ...   
7495      0.000000     0.000000          0.0           0.0      0.0       1   
7496      0.000000     0.000000          0.0           0.0      0.0       1   
7497      0.000000     0.133333          0.0           0.0      0.0       0   
7498      0.000000     0.000000          0.0           0.0      0.0       0   
7499      0.148148     0.000000          0.0           0.0      0.0       1   

      ...  diag_2_other  diag_2_respiratory  diag_3_circulatory  \
0     ...           0.0                 0.0                 0.0   
1     ...           0.0                 1.0                 1.0   
2     ...           0.0                 0.0                 1.0   
3     ...           0.0                 0.0                 0.0   
4     ...           0.0                 0.0                 1.0   
...   ...           ...                 ...                 ...   
7495  ...           1.0                 0.0                 0.0   
7496  ...           0.0                 0.0                 0.0   
7497  ...           0.0                 1.0                 0.0   
7498  ...           0.0                 0.0                 0.0   
7499  ...           0.0                 0.0                 1.0   

      diag_3_diabetes  diag_3_digestive  diag_3_injury  diag_3_missing  \
0                 0.0               0.0            0.0             0.0   
1                 0.0               0.0            0.0             0.0   
2                 0.0               0.0            0.0             0.0   
3                 0.0               0.0            0.0             0.0   
4                 0.0               0.0            0.0             0.0   
...               ...               ...            ...             ...   
7495              0.0               0.0            0.0             0.0   
7496              0.0               0.0            0.0             0.0   
7497              1.0               0.0            0.0             0.0   
7498              0.0               0.0            0.0             0.0   
7499              0.0               0.0            0.0             0.0   

      diag_3_musculoskeletal  diag_3_other  diag_3_respiratory  
0                        0.0           1.0                 0.0  
1                        0.0           0.0                 0.0  
2                        0.0           0.0                 0.0  
3                        0.0           1.0                 0.0  
4                        0.0           0.0                 0.0  
...                      ...           ...                 ...  
7495                     0.0   

In [5]:
y_train = pd.read_csv('../data/train_labels.csv').squeeze()
y_test = pd.read_csv('../data/test_labels.csv').squeeze()

In [6]:
y_train

0        0
1        1
2        0
3        0
4        0
        ..
17495    0
17496    0
17497    0
17498    0
17499    1
Name: readmission_status, Length: 17500, dtype: int64

In [7]:
y_test

0       1
1       0
2       0
3       0
4       1
       ..
7495    0
7496    1
7497    1
7498    1
7499    0
Name: readmission_status, Length: 7500, dtype: int64

In [8]:
model = SVC(
    probability=True,  # Essential for .predict_proba() and roc_auc_score
    random_state=42
)

In [9]:
print("Training SVM model...")
model.fit(X_train, y_train)
print("Training complete.")

Training SVM model...
Training complete.


In [10]:
y_pred_class = model.predict(X_test)

In [11]:
y_pred_class

array([1, 0, 0, ..., 0, 1, 0], shape=(7500,))

In [12]:
y_pred_class

array([1, 0, 0, ..., 0, 1, 0], shape=(7500,))

In [13]:
y_pred_proba = model.predict_proba(X_test)[:, 1]

In [14]:
y_pred_proba

array([0.5512446 , 0.34092802, 0.45208018, ..., 0.48444058, 0.52193761,
       0.43713088], shape=(7500,))

In [15]:
result = evaluate_model(model, X_test, y_test, "SVM", False)
print(result)

{'model_name': 'SVM', 'Accuracy': 0.6004, 'Precision': 0.6030315444489963, 'Recall (Sensitivity)': 0.4205714285714286, 'F1_Score': 0.4955394714694496, 'ROC_AUC': 0.6287949285714286, 'Confusion_Matrix_Values': {'True Negatives (TN)': 3031, 'False Positives (FP)': 969, 'False Negatives (FN)': 2028, 'True Positives (TP)': 1472}}


In [16]:
y_train[y_train == 0].count() / y_train.count()

np.float64(0.5283428571428571)

In [17]:
y_train[y_train == 1].count() / y_train.count()

np.float64(0.47165714285714283)

In [18]:
neg_count = np.sum(y_train == 0)
pos_count = np.sum(y_train == 1)
scale_pos_weight_value = neg_count / pos_count
print(f"Calculated scale_pos_weight: {scale_pos_weight_value:.2f}")

Calculated scale_pos_weight: 1.12


In [19]:
param_grid = {
    # C: Regularization parameter. Smaller C means stronger regularization.
    'C': [0.1, 1.0, 10], 
    
    # gamma: Kernel coefficient for 'rbf', 'poly', and 'sigmoid'. 
    # Small gamma means a large radius of influence (smoother boundary).
    'gamma': [0.01, 0.1, 'scale'], 
    
    # kernel: Radial Basis Function is standard for non-linear classification.
    'kernel': ['rbf'], 
    
    # class_weight: Crucial for handling class imbalance.
    'class_weight': ['balanced']
}

In [20]:
start_time = time.time()
print("\nStarting GridSearchCV...")

gscv = GridSearchCV(
    # Base Estimator: XGBoost Classifier (with fixed parameters)
    estimator=SVC(
        probability=True,  # Essential for .predict_proba() and roc_auc_score
        random_state=42
    ),
    
    # Search Space: The dictionary of hyperparameters
    param_grid=param_grid,
    
    # Scoring Metric: Use the AUC-ROC scorer defined above
    scoring='roc_auc',
    
    # Cross-Validation Folds: 5-fold is standard
    cv=5,
    
    # Verbosity: Shows progress during the search
    verbose=3,
    
    # Number of cores to use: -1 uses all available cores for speed
    n_jobs=-1
)

# This step trains hundreds of models based on the combinations in param_grid
gscv.fit(X_train, y_train)

end_time = time.time()
print(f"\nGrid Search completed in {(end_time - start_time) / 60:.2f} minutes.")


Starting GridSearchCV...
Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV 4/5] END C=0.1, class_weight=balanced, gamma=0.01, kernel=rbf;, score=0.555 total time= 7.2min
[CV 5/5] END C=0.1, class_weight=balanced, gamma=0.01, kernel=rbf;, score=0.562 total time= 7.2min
[CV 1/5] END C=0.1, class_weight=balanced, gamma=0.1, kernel=rbf;, score=0.597 total time= 7.3min
[CV 1/5] END C=0.1, class_weight=balanced, gamma=0.01, kernel=rbf;, score=0.572 total time= 7.3min
[CV 2/5] END C=0.1, class_weight=balanced, gamma=0.01, kernel=rbf;, score=0.578 total time= 7.4min
[CV 3/5] END C=0.1, class_weight=balanced, gamma=0.01, kernel=rbf;, score=0.573 total time= 7.4min
[CV 3/5] END C=0.1, class_weight=balanced, gamma=0.1, kernel=rbf;, score=0.594 total time= 7.4min
[CV 2/5] END C=0.1, class_weight=balanced, gamma=0.1, kernel=rbf;, score=0.598 total time= 7.5min
[CV 5/5] END C=0.1, class_weight=balanced, gamma=0.1, kernel=rbf;, score=0.589 total time= 8.0min
[CV 4/5] END C=0.1, class_w

In [22]:
print("\n--- Grid Search Results ---")
print(f"Best AUC-ROC Score achieved: {gscv.best_score_:.4f}")
print("Best Hyperparameters found:")
print(gscv.best_params_)

# Retrieve the best model object
best_svm_model = gscv.best_estimator_


--- Grid Search Results ---
Best AUC-ROC Score achieved: 0.6360
Best Hyperparameters found:
{'C': 10, 'class_weight': 'balanced', 'gamma': 0.01, 'kernel': 'rbf'}


Testing the best fit model on test data

In [23]:
y_test_proba = best_svm_model.predict_proba(X_test)[:, 1]
y_test_pred_class = best_svm_model.predict(X_test)

In [24]:
print('\nBest SVM Model Evaluation on Test Set:')
result = evaluate_model(best_svm_model, X_test, y_test, "SVM", True)
print(result)


Best SVM Model Evaluation on Test Set:
Metrics for SVM saved/updated in /media/anubhaw/Anubhaw/Projects/Hospital Readmission Prediction/results.json
{'model_name': 'SVM', 'Accuracy': 0.6046666666666667, 'Precision': 0.6033217458478177, 'Recall (Sensitivity)': 0.4462857142857143, 'F1_Score': 0.5130563310888487, 'ROC_AUC': 0.6386632857142858, 'Confusion_Matrix_Values': {'True Negatives (TN)': 2973, 'False Positives (FP)': 1027, 'False Negatives (FN)': 1938, 'True Positives (TP)': 1562}}


### Saving the model

In [25]:
try:
    os.makedirs('../models', exist_ok=True)
except Exception as e:
    print(f"An error occurred: {e}")

In [26]:
joblib.dump(best_svm_model, '../models/best_svm_model.joblib')

['../models/best_svm_model.joblib']